version: '3'
name: tabroom
services:
    db:
        image: mariadb:10.6
        volumes:
            - tabdata:/var/lib/mysql
            - ../sql/current-schema.sql:/docker-entrypoint-initdb.d/0-current-schema.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tabroom
            MYSQL_USER: tabroom 
            MYSQL_PASSWORD: tabroom 
        command: --innodb_buffer_pool_size=4GB --innodb_io_capacity=2000 --max_allowed_packet=1G

    tabroomapp:
        depends_on:
            - db
        build:
            context: ../../
            dockerfile: doc/docker/Dockerfile
        ports:
            - 8000:80
        restart: always
        environment:
            TABROOM_DB_HOST: db
            TABROOM_DB_USER: root 
            TABROOM_DB_PASSWORD: root
        volumes:
            - ../../:/www/tabroom:Z
volumes:
    tabdata:
