version: '3'
name: tabroom
services:
    db:
        image: mariadb:10.6
        volumes:
            - tabdata:/var/lib/mysql
            - ../init/grant.sql:/docker-entrypoint-initdb.d/0-grant.sql
            - ../sql/current-schema.sql:/docker-entrypoint-initdb.d/1-current-schema.sql
            - ./account-create.sql:/docker-entrypoint-initdb.d/2-account-create.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tabroom
            MYSQL_USER: tabroom 
            MYSQL_PASSWORD: tabroom 
        command: --innodb_buffer_pool_size=4GB --innodb_io_capacity=2000 --max_allowed_packet=1G
    # Original tabroom website
    tabroomapp:
        depends_on:
            - db
        build:
            context: ../../
            dockerfile: doc/docker/Dockerfile.tabroomapp
        ports:
            - 8000:80
        restart: always
        environment:
            TABROOM_DB_HOST: db
            TABROOM_DB_USER: root 
            TABROOM_DB_PASSWORD: root
        volumes:
            - ../../:/www/tabroom:Z
    # Nodejs api
    api:
        depends_on:
            - db
        build:
            context: ../../
            dockerfile: doc/docker/Dockerfile.api
        command: bash -c "rm -rf /usr/local/app/node_modules && npm run dev" # Clear out modules in wrong location then run
        env_file: .env
        environment:
            - PORT=${API_PORT:-10010}
            - DB_HOST=db
            - DB_PASS=tabroom
        ports:
            - 10010:10010
        volumes:
            - ../../api:/usr/local/app
    # React client
    client:
        depends_on:
            - api
        build:
            context: ../../
            dockerfile: doc/docker/Dockerfile.client
        command: bash -c "rm -rf /usr/local/app/node_modules && npm run start" # Clear out modules in wrong location then run
        env_file: .env
        environment:
            - NODE_ENV=development
            - HOST=
        ports:
            - 3000:3000
        volumes:
            - ../../client:/usr/local/app
volumes:
    tabdata:
