version: '3'
services:
    db:
        image: mariadb:5.5
        volumes:
            - tabdata:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tabroom
            MYSQL_USER: tabroom 
            MYSQL_PASSWORD: tabroom 
        command: --innodb_buffer_pool_size=4GB --innodb_io_capacity=2000 --max_allowed_packet=1G

    tabroomapp:
        depends_on:
            - db
        image: tabroom-app:latest
        ports:
            - 8000:80
        restart: always
        environment:
            TABROOM_DB_HOST: db
            TABROOM_DB_USER: root 
            TABROOM_DB_PASSWORD: root
        volumes:
            - /www/tabroom:/www/tabroom:Z
volumes:
    tabdata:
