name: Tabroom CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
    CI: true
    TZ: "America/Chicago"
    SUCCEEDED: ":white_check_mark: "
    SLACK_ICON: ":octocat:"
    SLACK_CHANNEL: "#tech-updates"
    SLACK_USERNAME: "Github Actions"
    SLACK_COLOR: "#de4e2b"
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    SLACK_TITLE: ":heavy_multiplication_x:"
    SLACK_FOOTER: "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|[tabroom:master]>"
    MSG_MINIMAL: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get node
      uses: actions/setup-node@v1
      with:
        node-version: 16.12.0

    - name: Install packages
      run: npm install
      working-directory: ./api

    - name: Lint
      run: npm run lint
      working-directory: ./api

    - name: Tests
      run: npm run test
      working-directory: ./api

    - name: If tests passed change SLACK_COLOR and SLACK_TITLE accordingly
      if: success()
      run: |
        echo "SLACK_COLOR=good" >> $GITHUB_ENV
        echo "SLACK_TITLE=${{ env.SUCCEEDED }}" >> $GITHUB_ENV

    - name: Send slack notification
      if: always()
      uses: rtCamp/action-slack-notify@v2.1.0
